-- Applies a palette (shape: { base_30 = {...}, base_16 = {...} }, see
-- lua/themes/onedark.lua) as the current highlight groups. Per-theme identity
-- (vim.g.colors_name, vim.o.background) is deliberately NOT set here -- each
-- colors/<name>.lua wrapper owns that.
return function(palette)
  local colors = palette.base_30
  local theme = palette.base_16

  -- Clear the previous theme's highlights/syntax links so switching (:SetTheme) leaves nothing stale.
  vim.cmd "hi clear"
  if vim.fn.exists "syntax_on" == 1 then
    vim.cmd "syntax reset"
  end

  local groups = {
    -- editor UI (base46 integrations/defaults.lua)
    Normal = { fg = theme.base05, bg = theme.base00 },
    Added = { fg = colors.green },
    Removed = { fg = colors.red },
    Changed = { fg = colors.yellow },
    MatchWord = { bg = colors.grey, fg = colors.white },
    MatchParen = { link = "MatchWord" },
    Pmenu = { bg = colors.one_bg },
    PmenuSbar = { bg = colors.one_bg },
    PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
    PmenuThumb = { bg = colors.grey },
    Comment = { fg = colors.light_grey },
    CursorLineNr = { fg = colors.white },
    LineNr = { fg = colors.grey },
    FloatBorder = { fg = colors.blue },
    FloatTitle = { fg = colors.white, bg = colors.grey },
    NormalFloat = { bg = colors.darker_black },
    NvimInternalError = { fg = colors.red },
    WinSeparator = { fg = colors.line },
    DevIconDefault = { fg = colors.red },
    Debug = { fg = theme.base08 },
    Directory = { fg = theme.base0D },
    Error = { fg = theme.base00, bg = theme.base08 },
    ErrorMsg = { fg = theme.base08, bg = theme.base00 },
    Exception = { fg = theme.base08 },
    FoldColumn = { bg = "none" },
    Folded = { fg = colors.light_grey, bg = colors.black2 },
    IncSearch = { fg = theme.base01, bg = theme.base09 },
    Macro = { fg = theme.base08 },
    ModeMsg = { fg = theme.base0B },
    MoreMsg = { fg = theme.base0B },
    Question = { fg = theme.base0D },
    Search = { fg = theme.base01, bg = theme.base0A },
    Substitute = { fg = theme.base01, bg = theme.base0A },
    SpecialKey = { fg = theme.base03 },
    TooLong = { fg = theme.base08 },
    Visual = { bg = theme.base02 },
    VisualNOS = { fg = theme.base08 },
    WarningMsg = { fg = theme.base08 },
    WildMenu = { fg = theme.base08, bg = theme.base0A },
    Title = { fg = theme.base0D },
    Conceal = { bg = "NONE" },
    Cursor = { fg = theme.base00, bg = theme.base05 },
    NonText = { fg = theme.base03 },
    SignColumn = { fg = theme.base03 },
    ColorColumn = { bg = colors.black2 },
    CursorColumn = { bg = theme.base01 },
    CursorLine = { bg = colors.black2 },
    QuickFixLine = { bg = theme.base01 },
    healthSuccess = { bg = colors.green, fg = colors.black },
    WinBar = { bg = "NONE" },
    WinBarNC = { bg = "NONE" },

    -- lazy.nvim UI
    LazyH1 = { bg = colors.green, fg = colors.black },
    LazyH2 = { fg = colors.red, bold = true, underline = true },
    LazyButton = { bg = colors.one_bg, fg = colors.light_grey },
    LazySpecial = { fg = colors.blue },
    LazyCommit = { fg = colors.green },
    LazyValue = { fg = colors.teal },
    LazyDir = { fg = theme.base05 },
    LazyUrl = { fg = theme.base05 },

    -- legacy syntax groups (base46 integrations/syntax.lua)
    Boolean = { fg = theme.base09 },
    Character = { fg = theme.base08 },
    Conditional = { fg = theme.base0E },
    Constant = { fg = theme.base09 },
    Define = { fg = theme.base0E, sp = "none" },
    Delimiter = { fg = theme.base0F },
    Float = { fg = theme.base09 },
    Variable = { fg = theme.base05 },
    Function = { fg = theme.base0D },
    Identifier = { fg = theme.base08, sp = "none" },
    Include = { fg = theme.base0D },
    Keyword = { fg = theme.base0E },
    Label = { fg = theme.base0A },
    Number = { fg = theme.base09 },
    Operator = { fg = theme.base05, sp = "none" },
    PreProc = { fg = theme.base0A },
    Repeat = { fg = theme.base0A },
    Special = { fg = theme.base0C },
    SpecialChar = { fg = theme.base0F },
    Statement = { fg = theme.base08 },
    StorageClass = { fg = theme.base0A },
    String = { fg = theme.base0B },
    Structure = { fg = theme.base0E },
    Tag = { fg = theme.base0A },
    Todo = { fg = theme.base0A, bg = theme.base01 },
    Type = { fg = theme.base0A, sp = "none" },
    Typedef = { fg = theme.base0A },

    -- treesitter groups (base46 integrations/treesitter.lua)
    ["@variable"] = { fg = theme.base05 },
    ["@variable.builtin"] = { fg = theme.base09 },
    ["@variable.parameter"] = { fg = theme.base08 },
    ["@variable.member"] = { fg = theme.base08 },
    ["@variable.member.key"] = { fg = theme.base08 },
    ["@module"] = { fg = theme.base08 },
    ["@constant"] = { fg = theme.base09 },
    ["@constant.builtin"] = { fg = theme.base09 },
    ["@constant.macro"] = { fg = theme.base08 },
    ["@string"] = { fg = theme.base0B },
    ["@string.regex"] = { fg = theme.base0C },
    ["@string.escape"] = { fg = theme.base0C },
    ["@character"] = { fg = theme.base08 },
    ["@number"] = { fg = theme.base09 },
    ["@number.float"] = { fg = theme.base09 },
    ["@annotation"] = { fg = theme.base0F },
    ["@attribute"] = { fg = theme.base0A },
    ["@error"] = { fg = theme.base08 },
    ["@keyword.exception"] = { fg = theme.base08 },
    ["@keyword"] = { fg = theme.base0E },
    ["@keyword.function"] = { fg = theme.base0E },
    ["@keyword.return"] = { fg = theme.base0E },
    ["@keyword.operator"] = { fg = theme.base0E },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.conditional"] = { fg = theme.base0E },
    ["@keyword.conditional.ternary"] = { fg = theme.base0E },
    ["@keyword.repeat"] = { fg = theme.base0A },
    ["@keyword.storage"] = { fg = theme.base0A },
    ["@keyword.directive.define"] = { fg = theme.base0E },
    ["@keyword.directive"] = { fg = theme.base0A },
    ["@function"] = { fg = theme.base0D },
    ["@function.builtin"] = { fg = theme.base0D },
    ["@function.macro"] = { fg = theme.base08 },
    ["@function.call"] = { fg = theme.base0D },
    ["@function.method"] = { fg = theme.base0D },
    ["@function.method.call"] = { fg = theme.base0D },
    ["@constructor"] = { fg = theme.base0C },
    ["@operator"] = { fg = theme.base05 },
    ["@reference"] = { fg = theme.base05 },
    ["@punctuation.bracket"] = { fg = theme.base0F },
    ["@punctuation.delimiter"] = { fg = theme.base0F },
    ["@symbol"] = { fg = theme.base0B },
    ["@tag"] = { fg = theme.base0A },
    ["@tag.attribute"] = { fg = theme.base08 },
    ["@tag.delimiter"] = { fg = theme.base0F },
    ["@text"] = { fg = theme.base05 },
    ["@text.emphasis"] = { fg = theme.base09 },
    ["@text.strike"] = { fg = theme.base0F, strikethrough = true },
    ["@type.builtin"] = { fg = theme.base0A },
    ["@definition"] = { sp = theme.base04, underline = true },
    ["@scope"] = { bold = true },
    ["@property"] = { fg = theme.base08 },
    ["@markup.heading"] = { fg = theme.base0D },
    ["@markup.raw"] = { fg = theme.base09 },
    ["@markup.link"] = { fg = theme.base08 },
    ["@markup.link.url"] = { fg = theme.base09, underline = true },
    ["@markup.link.label"] = { fg = theme.base0C },
    ["@markup.list"] = { fg = theme.base08 },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.quote"] = { bg = colors.black2 },
    ["@comment"] = { fg = colors.grey_fg },
    ["@comment.todo"] = { fg = colors.grey, bg = colors.white },
    ["@comment.warning"] = { fg = colors.black2, bg = theme.base09 },
    ["@comment.note"] = { fg = colors.black, bg = colors.blue },
    ["@comment.danger"] = { fg = colors.black2, bg = colors.red },
    ["@diff.plus"] = { fg = colors.green },
    ["@diff.minus"] = { fg = colors.red },
    ["@diff.delta"] = { fg = colors.light_grey },

    -- LSP (base46 integrations/lsp.lua)
    LspReferenceText = { bg = colors.one_bg3 },
    LspReferenceRead = { bg = colors.one_bg3 },
    LspReferenceWrite = { bg = colors.one_bg3 },
    DiagnosticHint = { fg = colors.purple },
    DiagnosticError = { fg = colors.red },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticInfo = { fg = colors.green },
    LspSignatureActiveParameter = { fg = colors.black, bg = colors.green },
    LspInlayHint = { bg = colors.black2, fg = colors.light_grey },

    -- telescope (base46 integrations/telescope.lua, "bordered" style -- configs/telescope.lua
    -- never disables telescope's default border, so this repo's telescope stays bordered)
    TelescopeNormal = { bg = colors.black },
    TelescopePromptNormal = { bg = colors.black },
    TelescopeBorder = { fg = colors.one_bg3 },
    TelescopePromptBorder = { fg = colors.one_bg3 },
    TelescopePromptTitle = { fg = colors.black, bg = colors.red },
    TelescopeResultsTitle = { fg = colors.black, bg = colors.green },
    TelescopePreviewTitle = { fg = colors.black, bg = colors.blue },
    TelescopePromptPrefix = { fg = colors.red, bg = colors.black },
    TelescopeSelection = { bg = colors.black2, fg = colors.white },
    TelescopeMatching = { bg = colors.one_bg, fg = colors.blue },
    TelescopeResultsDiffAdd = { fg = colors.green },
    TelescopeResultsDiffChange = { fg = colors.yellow },
    TelescopeResultsDiffDelete = { fg = colors.red },

    -- nvim-tree (base46 integrations/nvimtree.lua)
    NvimTreeNormal = { bg = colors.darker_black },
    NvimTreeNormalNC = { bg = colors.darker_black },
    NvimTreeEndOfBuffer = { fg = colors.darker_black },
    NvimTreeWinSeparator = { fg = colors.darker_black, bg = colors.darker_black },
    NvimTreeCursorLine = { bg = colors.black },
    -- upstream darkens colors.line via base46's change_hex_lightness helper (no equivalent here)
    NvimTreeIndentMarker = { fg = colors.line },
    NvimTreeFolderIcon = { fg = colors.folder_bg },
    NvimTreeFolderName = { fg = colors.folder_bg },
    NvimTreeEmptyFolderName = { fg = colors.folder_bg },
    NvimTreeOpenedFolderName = { fg = colors.folder_bg },
    NvimTreeFolderArrowOpen = { fg = colors.folder_bg },
    NvimTreeFolderArrowClosed = { fg = colors.grey_fg },
    NvimTreeRootFolder = { fg = colors.red, bold = true },
    NvimTreeSpecialFile = { fg = colors.yellow, bold = true },
    NvimTreeGitDirty = { fg = colors.red },
    NvimTreeGitNew = { fg = colors.yellow },
    NvimTreeGitDeleted = { fg = colors.red },
    NvimTreeGitIgnored = { fg = colors.light_grey },
    NvimTreeWindowPicker = { fg = colors.red, bg = colors.black2 },
    NvimTreeDiagnosticErrorFileHL = { link = "DiagnosticError" },
    NvimTreeDiagnosticErrorFolderHL = { link = "DiagnosticError" },
    NvimTreeDiagnosticWarnFileHL = { link = "DiagnosticWarn" },
    NvimTreeDiagnosticWarnFolderHL = { link = "DiagnosticWarn" },
    -- upstream links to base46's own "DiagnosticNormal" group, which doesn't exist here
    NvimTreeDiagnosticInfoFileHL = { link = "DiagnosticInfo" },
    NvimTreeDiagnosticInfoFolderHL = { link = "DiagnosticInfo" },
    NvimTreeDiagnosticHintFileHL = { link = "DiagnosticHint" },
    NvimTreeDiagnosticHintFolderHL = { link = "DiagnosticHint" },
  }

  for group, opts in pairs(groups) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end
