-- Palette + highlight groups ported from NvChad's base46 onedark theme
-- (base46/themes/onedark.lua + integrations/{defaults,syntax,treesitter,lsp}.lua),
-- hand-written here with zero external dependency. Plugin-specific theming
-- (lualine, bufferline, telescope, etc.) lives in each plugin's own config.

vim.cmd "hi clear"
if vim.fn.exists "syntax_on" == 1 then
  vim.cmd "syntax reset"
end

vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "onedark"

local colors = {
  white = "#abb2bf",
  darker_black = "#1b1f27",
  black = "#1e222a",
  black2 = "#252931",
  one_bg = "#282c34",
  one_bg2 = "#353b45",
  one_bg3 = "#373b43",
  grey = "#42464e",
  grey_fg = "#565c64",
  grey_fg2 = "#6f737b",
  light_grey = "#6f737b",
  red = "#e06c75",
  green = "#98c379",
  blue = "#61afef",
  purple = "#de98fd",
  teal = "#519ABA",
  yellow = "#e7c787",
  line = "#31353d",
  pmenu_bg = "#61afef",
}

local theme = {
  base00 = "#1e222a",
  base01 = "#353b45",
  base02 = "#3e4451",
  base03 = "#545862",
  base04 = "#565c64",
  base05 = "#abb2bf",
  base08 = "#e06c75",
  base09 = "#d19a66",
  base0A = "#e5c07b",
  base0B = "#98c379",
  base0C = "#56b6c2",
  base0D = "#61afef",
  base0E = "#c678dd",
  base0F = "#be5046",
}

local groups = {
  -- editor UI (base46 integrations/defaults.lua)
  Normal = { fg = theme.base05, bg = theme.base00 },
  Added = { fg = colors.green },
  Removed = { fg = colors.red },
  Changed = { fg = colors.yellow },
  MatchWord = { bg = colors.grey, fg = colors.white },
  MatchParen = { link = "MatchWord" },
  Pmenu = { bg = colors.one_bg },
  PmenuSbar = { bg = colors.one_bg },
  PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
  PmenuThumb = { bg = colors.grey },
  Comment = { fg = colors.light_grey },
  CursorLineNr = { fg = colors.white },
  LineNr = { fg = colors.grey },
  FloatBorder = { fg = colors.blue },
  FloatTitle = { fg = colors.white, bg = colors.grey },
  NormalFloat = { bg = colors.darker_black },
  NvimInternalError = { fg = colors.red },
  WinSeparator = { fg = colors.line },
  DevIconDefault = { fg = colors.red },
  Debug = { fg = theme.base08 },
  Directory = { fg = theme.base0D },
  Error = { fg = theme.base00, bg = theme.base08 },
  ErrorMsg = { fg = theme.base08, bg = theme.base00 },
  Exception = { fg = theme.base08 },
  FoldColumn = { bg = "none" },
  Folded = { fg = colors.light_grey, bg = colors.black2 },
  IncSearch = { fg = theme.base01, bg = theme.base09 },
  Macro = { fg = theme.base08 },
  ModeMsg = { fg = theme.base0B },
  MoreMsg = { fg = theme.base0B },
  Question = { fg = theme.base0D },
  Search = { fg = theme.base01, bg = theme.base0A },
  Substitute = { fg = theme.base01, bg = theme.base0A },
  SpecialKey = { fg = theme.base03 },
  TooLong = { fg = theme.base08 },
  Visual = { bg = theme.base02 },
  VisualNOS = { fg = theme.base08 },
  WarningMsg = { fg = theme.base08 },
  WildMenu = { fg = theme.base08, bg = theme.base0A },
  Title = { fg = theme.base0D },
  Conceal = { bg = "NONE" },
  Cursor = { fg = theme.base00, bg = theme.base05 },
  NonText = { fg = theme.base03 },
  SignColumn = { fg = theme.base03 },
  ColorColumn = { bg = colors.black2 },
  CursorColumn = { bg = theme.base01 },
  CursorLine = { bg = colors.black2 },
  QuickFixLine = { bg = theme.base01 },
  healthSuccess = { bg = colors.green, fg = colors.black },
  WinBar = { bg = "NONE" },
  WinBarNC = { bg = "NONE" },

  -- lazy.nvim UI
  LazyH1 = { bg = colors.green, fg = colors.black },
  LazyH2 = { fg = colors.red, bold = true, underline = true },
  LazyButton = { bg = colors.one_bg, fg = colors.light_grey },
  LazySpecial = { fg = colors.blue },
  LazyCommit = { fg = colors.green },
  LazyValue = { fg = colors.teal },
  LazyDir = { fg = theme.base05 },
  LazyUrl = { fg = theme.base05 },

  -- legacy syntax groups (base46 integrations/syntax.lua)
  Boolean = { fg = theme.base09 },
  Character = { fg = theme.base08 },
  Conditional = { fg = theme.base0E },
  Constant = { fg = theme.base09 },
  Define = { fg = theme.base0E, sp = "none" },
  Delimiter = { fg = theme.base0F },
  Float = { fg = theme.base09 },
  Variable = { fg = theme.base05 },
  Function = { fg = theme.base0D },
  Identifier = { fg = theme.base08, sp = "none" },
  Include = { fg = theme.base0D },
  Keyword = { fg = theme.base0E },
  Label = { fg = theme.base0A },
  Number = { fg = theme.base09 },
  Operator = { fg = theme.base05, sp = "none" },
  PreProc = { fg = theme.base0A },
  Repeat = { fg = theme.base0A },
  Special = { fg = theme.base0C },
  SpecialChar = { fg = theme.base0F },
  Statement = { fg = theme.base08 },
  StorageClass = { fg = theme.base0A },
  String = { fg = theme.base0B },
  Structure = { fg = theme.base0E },
  Tag = { fg = theme.base0A },
  Todo = { fg = theme.base0A, bg = theme.base01 },
  Type = { fg = theme.base0A, sp = "none" },
  Typedef = { fg = theme.base0A },

  -- treesitter groups (base46 integrations/treesitter.lua)
  ["@variable"] = { fg = theme.base05 },
  ["@variable.builtin"] = { fg = theme.base09 },
  ["@variable.parameter"] = { fg = theme.base08 },
  ["@variable.member"] = { fg = theme.base08 },
  ["@variable.member.key"] = { fg = theme.base08 },
  ["@module"] = { fg = theme.base08 },
  ["@constant"] = { fg = theme.base09 },
  ["@constant.builtin"] = { fg = theme.base09 },
  ["@constant.macro"] = { fg = theme.base08 },
  ["@string"] = { fg = theme.base0B },
  ["@string.regex"] = { fg = theme.base0C },
  ["@string.escape"] = { fg = theme.base0C },
  ["@character"] = { fg = theme.base08 },
  ["@number"] = { fg = theme.base09 },
  ["@number.float"] = { fg = theme.base09 },
  ["@annotation"] = { fg = theme.base0F },
  ["@attribute"] = { fg = theme.base0A },
  ["@error"] = { fg = theme.base08 },
  ["@keyword.exception"] = { fg = theme.base08 },
  ["@keyword"] = { fg = theme.base0E },
  ["@keyword.function"] = { fg = theme.base0E },
  ["@keyword.return"] = { fg = theme.base0E },
  ["@keyword.operator"] = { fg = theme.base0E },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.conditional"] = { fg = theme.base0E },
  ["@keyword.conditional.ternary"] = { fg = theme.base0E },
  ["@keyword.repeat"] = { fg = theme.base0A },
  ["@keyword.storage"] = { fg = theme.base0A },
  ["@keyword.directive.define"] = { fg = theme.base0E },
  ["@keyword.directive"] = { fg = theme.base0A },
  ["@function"] = { fg = theme.base0D },
  ["@function.builtin"] = { fg = theme.base0D },
  ["@function.macro"] = { fg = theme.base08 },
  ["@function.call"] = { fg = theme.base0D },
  ["@function.method"] = { fg = theme.base0D },
  ["@function.method.call"] = { fg = theme.base0D },
  ["@constructor"] = { fg = theme.base0C },
  ["@operator"] = { fg = theme.base05 },
  ["@reference"] = { fg = theme.base05 },
  ["@punctuation.bracket"] = { fg = theme.base0F },
  ["@punctuation.delimiter"] = { fg = theme.base0F },
  ["@symbol"] = { fg = theme.base0B },
  ["@tag"] = { fg = theme.base0A },
  ["@tag.attribute"] = { fg = theme.base08 },
  ["@tag.delimiter"] = { fg = theme.base0F },
  ["@text"] = { fg = theme.base05 },
  ["@text.emphasis"] = { fg = theme.base09 },
  ["@text.strike"] = { fg = theme.base0F, strikethrough = true },
  ["@type.builtin"] = { fg = theme.base0A },
  ["@definition"] = { sp = theme.base04, underline = true },
  ["@scope"] = { bold = true },
  ["@property"] = { fg = theme.base08 },
  ["@markup.heading"] = { fg = theme.base0D },
  ["@markup.raw"] = { fg = theme.base09 },
  ["@markup.link"] = { fg = theme.base08 },
  ["@markup.link.url"] = { fg = theme.base09, underline = true },
  ["@markup.link.label"] = { fg = theme.base0C },
  ["@markup.list"] = { fg = theme.base08 },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.quote"] = { bg = colors.black2 },
  ["@comment"] = { fg = colors.grey_fg },
  ["@comment.todo"] = { fg = colors.grey, bg = colors.white },
  ["@comment.warning"] = { fg = colors.black2, bg = theme.base09 },
  ["@comment.note"] = { fg = colors.black, bg = colors.blue },
  ["@comment.danger"] = { fg = colors.black2, bg = colors.red },
  ["@diff.plus"] = { fg = colors.green },
  ["@diff.minus"] = { fg = colors.red },
  ["@diff.delta"] = { fg = colors.light_grey },

  -- LSP (base46 integrations/lsp.lua)
  LspReferenceText = { bg = colors.one_bg3 },
  LspReferenceRead = { bg = colors.one_bg3 },
  LspReferenceWrite = { bg = colors.one_bg3 },
  DiagnosticHint = { fg = colors.purple },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.green },
  LspSignatureActiveParameter = { fg = colors.black, bg = colors.green },
  LspInlayHint = { bg = colors.black2, fg = colors.light_grey },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
